name: keras
channels:
  - conda-forge
  - defaults
dependencies:
  - imageio=2.8.0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - jupyter_client=6.0.0
  - jupyter_core=4.6.3
  - keras=2.3.1
  - keras-preprocessing=1.1.0
  - matplotlib=3.1.3
  - nbformat=5.0.4
  - numpy=1.18.1
  - pandas=1.0.1
  - pip=20.0.2
  - plotly=4.5.2
  - progressbar2=3.50.0
  - python=3.6.7
  - scikit-image=0.16.2
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - tensorflow=1.13.1
  - pillow
  - qutip
  - pip:
    - tqdm==4.31.1

